export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_RESPONSE_ACTION = 'LOGIN_RESPONSE_ACTION';
export const LOGIN_ERROR_RESPONSE_ACTION = 'LOGIN_ERROR_RESPONSE_ACTION';

export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const LOGOUT_RESPONSE_ACTION = 'LOGOUT_RESPONSE_ACTION';
export const LOGOUT_ERROR_RESPONSE_ACTION = 'LOGOUT_ERROR_RESPONSE_ACTION';
