export const SORT_RECIPES_ACTION = 'SORT_RECIPES_ACTION';
export const SEARCH_RECIPES_ACTION = 'SEARCH_RECIPES_ACTION';
export const SORT_MY_RECIPES_ACTION = 'SORT_MY_RECIPES_ACTION';
export const SEARCH_MY_RECIPES_ACTION = 'SEARCH_MY_RECIPES_ACTION';
export const SELECT_RECIPE_ACTION = 'SELECT_RECIPE_ACTION';

export const GET_ALL_RECIPES_ACTION = 'GET_ALL_RECIPES_ACTION';
export const GET_ALL_RECIPES_RESPONSE_ACTION = 'GET_ALL_RECIPES_RESPONSE_ACTION';
export const GET_ALL_RECIPES_ERROR_RESPONSE_ACTION = 'GET_ALL_RECIPES_ERROR_RESPONSE_ACTION';

export const GET_MY_RECIPES_ACTION = 'GET_MY_RECIPES_ACTION';
export const GET_MY_RECIPES_RESPONSE_ACTION = 'GET_MY_RECIPES_RESPONSE_ACTION';
export const GET_MY_RECIPES_ERROR_RESPONSE_ACTION = 'GET_MY_RECIPES_ERROR_RESPONSE_ACTION';

export const CREATE_RECIPE_ACTION = 'CREATE_RECIPE_ACTION';
export const CREATE_RECIPE_RESPONSE_ACTION = 'CREATE_RECIPE_RESPONSE_ACTION';
export const CREATE_RECIPE_ERROR_RESPONSE_ACTION = 'CREATE_RECIPE_ERROR_RESPONSE_ACTION';

export const GET_RECIPE_ACTION = 'GET_RECIPE_ACTION';
export const GET_RECIPE_RESPONSE_ACTION = 'GET_RECIPE_RESPONSE_ACTION';
export const GET_RECIPE_ERROR_RESPONSE_ACTION = 'GET_RECIPE_ERROR_RESPONSE_ACTION';

export const UPDATE_RECIPE_ACTION = 'UPDATE_RECIPE_ACTION';
export const UPDATE_RECIPE_RESPONSE_ACTION = 'UPDATE_RECIPE_RESPONSE_ACTION';
export const UPDATE_RECIPE_ERROR_RESPONSE_ACTION = 'UPDATE_RECIPE_ERROR_RESPONSE_ACTION';

export const SAVE_RECIPE_ACTION = 'SAVE_RECIPE_ACTION';
export const SAVE_RECIPE_RESPONSE_ACTION = 'SAVE_RECIPE_RESPONSE_ACTION';
export const SAVE_RECIPE_ERROR_RESPONSE_ACTION = 'SAVE_RECIPE_ERROR_RESPONSE_ACTION';

export const UNSAVE_RECIPE_ACTION = 'UNSAVE_RECIPE_ACTION';
export const UNSAVE_RECIPE_RESPONSE_ACTION = 'UNSAVE_RECIPE_RESPONSE_ACTION';
export const UNSAVE_RECIPE_ERROR_RESPONSE_ACTION = 'UNSAVE_RECIPE_ERROR_RESPONSE_ACTION';

export const ADD_INGREDIENT_TO_RECIPE_ACTION = 'ADD_INGREDIENT_TO_RECIPE_ACTION';
export const ADD_INGREDIENT_TO_RECIPE_RESPONSE_ACTION = 'ADD_INGREDIENT_TO_RECIPE_RESPONSE_ACTION';
export const ADD_INGREDIENT_TO_RECIPE_ERROR_RESPONSE_ACTION = 'ADD_INGREDIENT_TO_RECIPE_ERROR_RESPONSE_ACTION';

export const UPDATE_INGREDIENT_ON_RECIPE_ACTION = 'UPDATE_INGREDIENT_ON_RECIPE_ACTION';
export const UPDATE_INGREDIENT_ON_RECIPE_RESPONSE_ACTION = 'UPDATE_INGREDIENT_ON_RECIPE_RESPONSE_ACTION';
export const UPDATE_INGREDIENT_ON_RECIPE_ERROR_RESPONSE_ACTION = 'UPDATE_INGREDIENT_ON_RECIPE_ERROR_RESPONSE_ACTION';

export const REMOVE_INGREDIENTS_FROM_RECIPE_ACTION = 'REMOVE_INGREDIENTS_FROM_RECIPE_ACTION';
export const REMOVE_INGREDIENTS_FROM_RECIPE_RESPONSE_ACTION = 'REMOVE_INGREDIENTS_FROM_RECIPE_RESPONSE_ACTION';
export const REMOVE_INGREDIENTS_FROM_RECIPE_ERROR_RESPONSE_ACTION = 'REMOVE_INGREDIENTS_FROM_RECIPE_ERROR_RESPONSE_ACTION';

export const ADD_DIRECTION_TO_RECIPE_ACTION = 'ADD_DIRECTION_TO_RECIPE_ACTION';
export const ADD_DIRECTION_TO_RECIPE_RESPONSE_ACTION = 'ADD_DIRECTION_TO_RECIPE_RESPONSE_ACTION';
export const ADD_DIRECTION_TO_RECIPE_ERROR_RESPONSE_ACTION = 'ADD_DIRECTION_TO_RECIPE_ERROR_RESPONSE_ACTION';

export const UPDATE_DIRECTION_ON_RECIPE_ACTION = 'UPDATE_DIRECTION_ON_RECIPE_ACTION';
export const UPDATE_DIRECTION_ON_RECIPE_RESPONSE_ACTION = 'UPDATE_DIRECTION_ON_RECIPE_RESPONSE_ACTION';
export const UPDATE_DIRECTION_ON_RECIPE_ERROR_RESPONSE_ACTION = 'UPDATE_DIRECTION_ON_RECIPE_ERROR_RESPONSE_ACTION';

export const REMOVE_DIRECTION_FROM_RECIPE_ACTION = 'REMOVE_DIRECTION_FROM_RECIPE_ACTION';
export const REMOVE_DIRECTION_FROM_RECIPE_RESPONSE_ACTION = 'REMOVE_DIRECTION_FROM_RECIPE_RESPONSE_ACTION';
export const REMOVE_DIRECTION_FROM_RECIPE_ERROR_RESPONSE_ACTION = 'REMOVE_DIRECTION_FROM_RECIPE_ERROR_RESPONSE_ACTION';

export const ADD_NOTE_TO_RECIPE_ACTION = 'ADD_NOTE_TO_RECIPE_ACTION';
export const ADD_NOTE_TO_RECIPE_RESPONSE_ACTION = 'ADD_NOTE_TO_RECIPE_RESPONSE_ACTION';
export const ADD_NOTE_TO_RECIPE_ERROR_RESPONSE_ACTION = 'ADD_NOTE_TO_RECIPE_ERROR_RESPONSE_ACTION';

export const UPDATE_NOTE_ON_RECIPE_ACTION = 'UPDATE_NOTE_ON_RECIPE_ACTION';
export const UPDATE_NOTE_ON_RECIPE_RESPONSE_ACTION = 'UPDATE_NOTE_ON_RECIPE_RESPONSE_ACTION';
export const UPDATE_NOTE_ON_RECIPE_ERROR_RESPONSE_ACTION = 'UPDATE_NOTE_ON_RECIPE_ERROR_RESPONSE_ACTION';

export const REMOVE_NOTE_FROM_RECIPE_ACTION = 'REMOVE_NOTE_FROM_RECIPE_ACTION';
export const REMOVE_NOTE_FROM_RECIPE_RESPONSE_ACTION = 'REMOVE_NOTE_FROM_RECIPE_RESPONSE_ACTION';
export const REMOVE_NOTE_FROM_RECIPE_ERROR_RESPONSE_ACTION = 'REMOVE_NOTE_FROM_RECIPE_ERROR_RESPONSE_ACTION';
