export const GET_USER_ME_ACTION = 'GET_USER_ME_ACTION';
export const GET_USER_ME_RESPONSE_ACTION = 'GET_USER_ME_RESPONSE_ACTION';
export const GET_USER_ME_ERROR_RESPONSE_ACTION = 'GET_USER_ME_ERROR_RESPONSE_ACTION';
